services:
  bq-notifier-build:
    build:
      context: .
      dockerfile: ./docker/notifier/Dockerfile.prod
    image: blockqueue/notifier:latest

  bq-example-notifier-service:
    build:
      context: ./examples/notifier-service
      dockerfile: Dockerfile
      args:
        NOTIFIER_IMAGE: blockqueue/notifier:latest
    image: blockqueue/example-notifier-service:latest
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
      - NOTIFIER_SIGNING_SECRET=wefeqfdwfwrfqfweq9343rrwfeafeqr42r432ef
      - MAIL_FROM_EMAIL=noreply@example.com
      - ZEPTOMAIL_API_KEY=your-api-key
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=your-access-key-id
      - AWS_SECRET_ACCESS_KEY=your-secret-access-key
      - TERMII_API_KEY=your-termii-api-key
      - TERMII_FROM=MyApp
    depends_on:
      - bq-notifier-build
