services:
  bq-notifier-build:
    build:
      context: .
      dockerfile: ./docker/notifier/Dockerfile.prod
    image: blockqueue/notifier:latest
    command: ['-e', 'process.exit(0)']

  bq-example-notifier-service:
    build:
      context: ./examples/notifier-service
      dockerfile: Dockerfile
      args:
        NOTIFIER_IMAGE: notifier
      additional_contexts:
        notifier: service:bq-notifier-build
    image: blockqueue/example-notifier-service:latest
    ports:
      - '3000:3000'
    env_file:
      - ./apps/notifier/.env.example
    depends_on:
      bq-notifier-build:
        condition: service_completed_successfully
