services:
  bq-notifier-build:
    build:
      context: .
      dockerfile: ./docker/notifier/Dockerfile.prod
    image: blockqueue/notifier:latest

  bq-example-notifier-service:
    build:
      context: ./examples/notifier-service
      dockerfile: Dockerfile
      args:
        NOTIFIER_IMAGE: blockqueue/notifier:latest
    image: blockqueue/example-notifier-service:latest
    ports:
      - '3000:3000'
    env_file:
      - ./apps/notifier/.env
    depends_on:
      - bq-notifier-build
